# Generated by Django 5.0 on 2024-04-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_quoteproduct_remove_quoterequest_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='product',
            new_name='products',
        ),
    ]
