# Generated by Django 5.0 on 2024-04-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_rename_product_quoterequest_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='quote.quoteproduct'),
        ),
    ]
