# Generated by Django 5.0 on 2024-04-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_quoterequest_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteproduct',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='tax',
        ),
    ]
