# Generated by Django 5.0 on 2024-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_remove_quoteproduct_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteproduct',
            name='description',
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
