# Generated by Django 5.0 on 2024-05-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_remove_quoteproduct_description_quoteproduct_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='products',
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (Per Product)'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='quote',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='quote.quoterequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='TAX'),
        ),
    ]
