# Generated by Django 5.0 on 2024-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_remove_quoterequest_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteproduct',
            name='new_name',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='New Name'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='new_notes',
            field=models.TextField(blank=True, null=True, verbose_name='New Notes'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='new_quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='New Quantity'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='new_unit',
            field=models.CharField(blank=True, choices=[('bag', 'Bag / Bags'), ('barrel', 'Barrel / Barrels'), ('bushel', 'Bushel / Bushels'), ('cubic', 'Cubic Meter / Cubic Meters'), ('dozen', 'Dozen / Dozens'), ('gallon', 'Gallon / Gallons'), ('gram', 'Gram / Grams'), ('kilogram', 'Kilogram / Kilograms'), ('kilometer', 'Kilometer / Kilometers'), ('long', 'Long Ton / Long Tons'), ('meter', 'Meter / Meters'), ('metric', 'Metric Ton / Metric Tons'), ('ounce', 'Ounce / Ounces'), ('pair', 'Pair / Pairs'), ('pack', 'Pack / Packs'), ('piece', 'Piece / Pieces'), ('pound', 'Pound / Pounds'), ('set', 'Set / Sets'), ('short', 'Short Ton / Short Tons'), ('square', 'Square Meter / Square Meters'), ('ton', 'Ton / Tons')], max_length=50, null=True, verbose_name='New Unit'),
        ),
    ]
