# Generated by Django 5.0 on 2024-05-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_quoteproduct_new_name_quoteproduct_new_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteoffer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='quoteoffer',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='quoteoffer',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quoteoffer',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='quoteoffer',
            name='total_price',
        ),
    ]
