# Generated by Django 5.0 on 2024-05-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_remove_quoteoffer_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteproduct',
            name='new_name',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='new_notes',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='new_quantity',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='new_unit',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='tax',
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('bag', 'Bag / Bags'), ('barrel', 'Barrel / Barrels'), ('bushel', 'Bushel / Bushels'), ('cubic', 'Cubic Meter / Cubic Meters'), ('dozen', 'Dozen / Dozens'), ('gallon', 'Gallon / Gallons'), ('gram', 'Gram / Grams'), ('kilogram', 'Kilogram / Kilograms'), ('kilometer', 'Kilometer / Kilometers'), ('long', 'Long Ton / Long Tons'), ('meter', 'Meter / Meters'), ('metric', 'Metric Ton / Metric Tons'), ('ounce', 'Ounce / Ounces'), ('pair', 'Pair / Pairs'), ('pack', 'Pack / Packs'), ('piece', 'Piece / Pieces'), ('pound', 'Pound / Pounds'), ('set', 'Set / Sets'), ('short', 'Short Ton / Short Tons'), ('square', 'Square Meter / Square Meters'), ('ton', 'Ton / Tons')], max_length=50, verbose_name='Unit')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (Per Product)')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='TAX')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quoteoffer')),
            ],
        ),
    ]
