# Generated by Django 5.0 on 2024-05-10 07:30

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_user_parent_alter_user_shipping_address'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('payment_method', models.CharField(choices=[('DIR', 'Direct'), ('DIV', 'Divided')], max_length=3, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('O', 'Open'), ('CL', 'Closed'), ('CA', 'Canceled'), ('P', 'Pending Payment'), ('F', 'Finished')], default='O', max_length=2, verbose_name='Status')),
                ('delivery_time', models.DateTimeField()),
                ('payment_days', models.CharField(max_length=255)),
                ('opportunity_value', models.CharField(choices=[('VS', 'Very Small'), ('S', 'Small'), ('M', 'Medium'), ('B', 'Big'), ('E', 'Extraordinary')], max_length=3, verbose_name='Opportunity Value')),
                ('views', models.BigIntegerField(default=0, verbose_name='Views')),
                ('delivery_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('target_suppliers', models.ManyToManyField(related_name='target_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Target Suppliers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
