# Generated by Django 5.0 on 2024-05-10 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_target_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
