# Generated by Django 5.0 on 2024-05-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunity_created_opportunity_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='delivery_location',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='delivery_time',
            new_name='delivery_date',
        ),
    ]
