# Generated by Django 5.0 on 2026-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_rename_delivery_location_opportunity_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
    ]
